name: Build Dylib

on:
  push:
    branches:
      - master
      - dev
    # tags: '*'
  release:
    types:
      - created
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.3]
        julia-arch: [x64]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Julia
        uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - name: Install dependencies
        run: julia -e 'using Pkg; Pkg.add("BinaryProvider"); Pkg.add("BinaryBuilder");'
      - name: Build
        env:
          BINARYBUILDER_DOWNLOADS_CACHE: downloads
          BINARYBUILDER_AUTOMATIC_APPLE: true
        run: julia deps/build_tarballs.jl
      - name: Upload to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: deps/gh-update-to-release
